apiVersion: v1
kind: Service
metadata:
  name: {{ "svn" }}
  labels:
    app: {{ "svn" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 3960
      targetPort: 3960
      protocol: TCP
      name: co
  selector:
    app: {{ "svn" }}
    release: {{ .Release.Name }}
